version: "2"
services:
    kanboard:
        environment:
            - PLUGIN_INSTALLER=true
        image: kanboard/kanboard:latest
        ports:
            - "8069:80"
            - "443:443"
        volumes:
            - kanboard_data:/var/www/app/data
            - kanboard_plugins:/var/www/app/plugins
            - kanboard_ssl:/etc/nginx/ssl
volumes:
    kanboard_data:
    kanboard_plugins:
    kanboard_ssl:
